[package]
name = "envoy-control-plane"
version = "0.3.0"
license = "Apache-2.0"
edition = "2021"
build = "build.rs"
description = "Envoy xDS v3 APIs"
repository = "https://github.com/bpowers/rust-envoy-control-plane"

[dependencies]
prost = "0.9"
prost-types = "0.9"
tonic = { version = "0.6", default-features = false, optional = true }
pbjson = { version = "0.2", git = "https://github.com/bpowers/pbjson", rev = "a362f9ab4240ee42f011fe6c471d65a70eedc1fc", optional = true }
pbjson-types = { version = "0.2", git = "https://github.com/bpowers/pbjson", rev = "a362f9ab4240ee42f011fe6c471d65a70eedc1fc", optional = true }
serde = { version = "1", optional = true }

[build-dependencies]
prost-build = "0.9"
tonic-build = { version = "0.6", optional = true }
pbjson-build = { version = "0.2", git = "https://github.com/bpowers/pbjson", rev = "a362f9ab4240ee42f011fe6c471d65a70eedc1fc", optional = true }

[features]
grpc = ["tonic/async-trait", "tonic/codegen", "tonic/prost", "tonic/transport", "tonic-build"]
json = ["pbjson", "pbjson-build", "pbjson-types", "serde"]
default = ["grpc", "json"]
